# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2b081292a97e000b09b73aa85c7ab086e5ab0098c71ce6b497fba9313348ce2ff3080564b3a1ace166c402118f984d8640df860ecf79a500c36a56e81ba8e70

test:
  secret_key_base: 85ce5e325b0bfeb77a2fe7fc23a4d2da2052a903bfee50859df62b8afab0ce985c951d278f63b53271ca2b93aeed90489dfc235d893876de440820dfeed588e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
